# Generated by Django 4.2.16 on 2024-11-25 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=9)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.actor')),
            ],
        ),
        migrations.CreateModel(
            name='WorldCupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('actor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_actor1', to='movies.actor')),
                ('actor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_actor2', to='movies.actor')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup.worldcupgame')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='movies.actor')),
            ],
        ),
    ]
